### ISSUE TITLE
Change page title dynamically

### ISSUE THREAD

**Issue by mirekdlugosz** [mirekdlugosz/create-pokemon-team#1]
All of our pages display the same title. It should change automatically, so going to https://createpokemon.team/about displays "About - createPokémon.​team".

See https://toddmotto.com/dynamic-page-titles-angular-2-router-events

**Comment by aes421** [comment]
I believe this is already working on the site isn't it?

**Comment by mirekdlugosz** [comment]
Partly. Text in `<header>` is correctly set, but `<title>` remains static. PR #21 was opened to tackle these problems, but it didn't work in all cases and was not merged.

**Comment by aes421** [comment]
Got it.  I can work on this.

**Comment by mirekdlugosz** [comment]
Sure, feel free :) .

Also, if you would be interested in contributing further:
1. I created a bunch of issues recently and organized them in project. Most of them are for data reader backend (Python), though.
2. Automatic tests for frontend are almost non-existent. I'm not very familiar with current JavaScript testing frameworks, so improving/setting infrastructure is one option. Increasing test coverage is another option. That is especially important since we are already behind in Angular versions, but right now it's getting hard to get confidence that updating version won't completely break everything.
